#应用程序端口配置
server: 
  port: 80
#  tomcat:
#    access-log-enabled: true

#日志配置
logging:
#    file:
#    path:
    config: classpath:logback.xml
#    level:
#        org.springframework.web: ERROR
#        org.springframework.beans: ERROR